name: My first githup actions
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"
      - name: Install node_modules
        run: npm
      - name: Build the project
        run: npm build
      - name: Setup finis
        run: echo "hurray!"
